version: '3.7'

services:
  svelte:
    image: svelte-template:dev
    build:
      context: .
    volumes:
      - ".:/usr/src/app"
    ports:
      - "5000:5000"
      - "35729:35729"
    networks:
      - svelte

networks:
  svelte: